name: Lint

on:
  push:
    branches: [ main ]

jobs:
  run-linters:
    name: Run linters
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
        include:
          - environment-file: .github/environments/environment.yml

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies from environment file
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r ${{ matrix.environment-file }}

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          flake8: true
