name: Test Bikeability with Conda

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          python-version: ${{ matrix.python-version }}
          environment-file: .github/environments/test-environment.yml
          activate-environment: bikeability-env

      - name: Verify Conda environment
        run: |
          conda info --envs
          conda list
          which python
          python -m pytest --version
        shell: bash

      - name: Install bikeability
        run: pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple bikeability
        shell: bash

      - name: Run tests
        run: pytest tests/
        shell: bash
