name: Lint and Test Bikeability

on:
  push:
    branches: [ main ]

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.10' ]
        include:
          - environment-file: .github/environments/requirements-bikeability.txt

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements-bikeability.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m venv bikeability
          source bikeability/bin/activate
          python -m pip install --upgrade pip
          pip install -r ${{ matrix.environment-file }}
        shell: bash

      - name: Run linters
        run: |
          source bikeability/bin/activate
          black .
          flake8 . --max-line-length=150
        shell: bash

      - name: Install bikeability from TestPyPI
        run: |
          source bikeability/bin/activate
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple bikeability
        shell: bash

      - name: Run tests
        run: |
          source bikeability/bin/activate
          pytest tests/
        shell: bash
