name: Test Bikeability with Conda

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
        include:
          - environment-file: .github/environments/test-environment.yml

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          environment-file: ${{ matrix.environment-file }}
          activate-environment: bikeability-env
          auto-update-conda: true

      - name: Install bikeability
        run: |
          eval "$(conda shell.bash hook)"
          conda activate bikeability-env
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple bikeability
        shell: bash

      - name: Run tests
        run: | 
          eval "$(conda shell.bash hook)"
          conda activate bikeability-env
          pytest tests/
        shell: bash
