name: Test Bikeability on Ubuntu

on:
  push:
    branches: [ main, fork/johanngrobe/chore/dependencies-update ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', "3.11", "3.12"]
 #       include:
 #         - environment-file: .github/environments/requirements-bikeability.txt

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}

#      - name: Cache pip dependencies
#        uses: actions/cache@v3
#        with:
#          path: ~/.cache/pip
#          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('requirements.txt') }}
#          restore-keys: |
#            ${{ runner.os }}-pip-${{ matrix.python-version }}

#      - name: Install dependencies
#        run: |
#          python -m venv bikeability
#          source bikeability/bin/activate
#          python -m pip install --upgrade pip
#          pip install -r ${{ matrix.environment-file }}
#        shell: bash

      - name: Install bikeability from TestPyPI
        run: |
          source bikeability/bin/activate
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple bikeability
        shell: bash

      - name: Run tests
        run: |
          source bikeability/bin/activate
          pytest tests/
        shell: bash
