name: Test Bikeability on different OS


on:
  push:
    branches: [ main ]


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10']


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create and update virtual environment
        run: | 
          python -m venv bikeability
          if [[ "$OSTYPE" == "msys" ]]; then
            source bikeability/Scripts/activate
          else
            source bikeability/bin/activate
          fi
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pip install pytest
        shell: bash

      - name: Install bikeability
        run: |
          if [[ "$OSTYPE" == "msys" ]]; then
            source bikeability/Scripts/activate
          else
            source bikeability/bin/activate
          fi
          pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple bikeability

      - name: Run tests
        run: |
          if [[ "$OSTYPE" == "msys" ]]; then
            source bikeability/Scripts/activate
          else
            source bikeability/bin/activate
          fi
          pytest tests/
